# Generated by Django 4.2.6 on 2023-10-29 15:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0003_post_comments_count_post_is_private_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Trend",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hashtag", models.CharField(max_length=255)),
                ("occurences", models.IntegerField()),
            ],
        ),
    ]
